version: '3.9'
services:
  db:
    image: mysql
    container_name: pokemon-database
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    volumes:
      - database-volume:/var/lib/mysql
volumes:
  database-volume:
